/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ChiTietHDDAO;
import dao.ChiTietPNDAO;
import dao.NhaCCDAO;
import dao.PhieuNhapDAO;
import dao.SanPhamDAO;
import static gui.FrmMain.indexHD;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.NhaCungCap;
import pojo.PhieuNhap;
import pojo.SanPham;

/**
 *
 * @author nguye
 */
public class frmNhapHang extends javax.swing.JFrame {

    /**
     * Creates new form frmNhapHang
     */
    static ArrayList<NhaCungCap> DSNCC=NhaCCDAO.layDSNCC();
    static int MaNV=0;
    DefaultTableModel dtm= new DefaultTableModel();
    DefaultTableModel dtm2= new DefaultTableModel();
    DefaultTableModel dtm3= new DefaultTableModel();
    public frmNhapHang(int ma) {
        MaNV=ma;
       
        initComponents();
        tbSanPhamNhap.setModel(dtm);
        String[] tieude={"MaSP","TenSP","Ma Loai","Don Gia","So Luong Ton Kho"};
        String[] tieude2={"id sản phẩm","Tên sản phẩm","Số Lượng"};
        String[] tieude3={"Mã Phiếu Nhập","Ma Nhà cung cấp","Mã Nhân Vien","Ngày Lập","Tồng tiền"};
        this.setLocationRelativeTo(null);
        
        
        dtm3.setColumnIdentifiers(tieude3);
        tbPhieuNhap.setModel(dtm3);
        dtm.setColumnIdentifiers(tieude);
        dtm2.setColumnIdentifiers(tieude2);
        tbGioHangNhap.setModel(dtm2);
        load();
        loadNCC();
        loadPN();
    }

    private frmNhapHang() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        public void load(){
        dtm.setRowCount(0);
        ArrayList<SanPham> dssp= SanPhamDAO.layDSSP();
        for(SanPham sp:dssp){
            Vector<Object> row= new Vector<Object>();
            row.add(sp.getMaSP());
            row.add(sp.getTenSP());
            row.add(sp.getMaLoai());
            row.add(sp.getDonGua());
            row.add(sp.getSoLuongTon());
            dtm.addRow(row);
        }
    }
        
        public void loadNCC(){
            DSNCC= NhaCCDAO.layDSNCC();
            cboNCC.removeAllItems();
            for(NhaCungCap ncc:DSNCC){
                cboNCC.addItem(ncc.getTenNCC());
            }
        }
        public int layIDNCC(String ten){
            DSNCC=NhaCCDAO.layDSNCC();
            for(NhaCungCap ncc: DSNCC){
                if(cboNCC.getSelectedItem().toString().equals(ncc.getTenNCC())){
                return ncc.getMaNCC();
                }
                
            }
            return -1;
        }
        public  void loadPN(){
            dtm3.setRowCount(0);
            ArrayList<PhieuNhap> Dspn=PhieuNhapDAO.layDSPN();
            for(PhieuNhap pn:Dspn){
                Vector<Object> row= new Vector<>();
                row.add(pn.getMaPN());
                row.add(pn.getMaNCC());
                row.add(pn.getMaNV());
                row.add(pn.getNgayLap());
                row.add(pn.getTongTien());
                dtm3.addRow(row);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemKHM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPhamNhap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGioHangNhap = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        cboNCC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPhieuNhap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThemKHM.setText("Thêm");
        btnThemKHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHMActionPerformed(evt);
            }
        });

        tbSanPhamNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSanPhamNhap);

        tbGioHangNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Sản phẩm", "Id Sản phẩm", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbGioHangNhap);

        btnThem.setText("Thêm vào giỏ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa khỏi giỏ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhà cung cấp");

        tbPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbPhieuNhap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 528, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(btnThem)
                                        .addGap(60, 60, 60)
                                        .addComponent(btnXoa)
                                        .addGap(61, 61, 61)
                                        .addComponent(btnNhap)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(522, 522, 522)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnThemKHM)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnThemKHM))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHMActionPerformed
        // TODO add your handling code here:
 

    }//GEN-LAST:event_btnThemKHMActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       String soLuong = JOptionPane.showInputDialog("Nhập số lượng:");
        int index = tbSanPhamNhap.getSelectedRow();
        int soluongS= Integer.parseInt(soLuong);
        
            Vector<Object> row= new Vector<>();
            row.add(tbSanPhamNhap.getValueAt(index,0));
            row.add(tbSanPhamNhap.getValueAt(index,1));
            row.add(soluongS);
            dtm2.addRow(row);
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int indexGH= tbGioHangNhap.getSelectedRow();
        dtm2.removeRow(indexGH);

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
            // TODO add your handling code here:
             Date currentDate = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String formattedDate = dateFormat.format(currentDate);
            PhieuNhapDAO.themPN(layIDNCC(cboNCC.getSelectedItem().toString()),MaNV,formattedDate );
            
            int IdPN=PhieuNhapDAO.layMaPNMoiNhat();
            for (int i = 0; i < dtm2.getRowCount(); i++) {
            int masp= Integer.parseInt(tbGioHangNhap.getValueAt(i,0).toString());
            
            int soluong= Integer.parseInt(tbGioHangNhap.getValueAt(i,2).toString());
                ChiTietPNDAO.themCtPN(IdPN, masp, soluong);
            }
            loadPN();
        
        

    }//GEN-LAST:event_btnNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmNhapHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemKHM;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbGioHangNhap;
    private javax.swing.JTable tbPhieuNhap;
    private javax.swing.JTable tbSanPhamNhap;
    // End of variables declaration//GEN-END:variables
}
